import type { PageContent } from './site';
import { applyTrustLine } from './site';

export const realtorsContent: PageContent = {
  hero: {
    eyebrow: 'Authority Day · For Top Realtors',
    titleLines: [
      'What we did for Roger.',
      'Now for the next 10',
      'top realtors.',
    ],
    body: 'One day. One trip. A complete online presence built around you — the way we built it for Roger Pettingell.',
    proof: '',
    primaryCta: 'Apply for Authority Day',
    secondaryCta: 'Watch the story',
    scrollPrompt: 'Watch the story',
    applyHref: '#apply',
    videoHref: '#vsl',
    image: '/assets/roger-hero.png',
    imageAlt: 'Authority Day for top realtors',
  },
  vsl: {
    eyebrow: '',
    title: '',
    subhead: '',
    posterEyebrow: 'The first impression',
    posterTitle: 'The whole system at work',
    caption:
      "That's the first impression. Here's what happens when the whole system goes to work.",
    ariaLabel: 'Play the overview of the content system',
    poster: '/assets/realtors-vsl-poster.jpg',
    videoSrcMP4: '/videos/realtors-vsl-1080p.mp4',
    videoSrcWEBM: '',
  },
  proofBand: {
    eyebrow: 'Roger Pettingell. Eighteen months.',
    caption:
      'A reputation that finally works online the way it works in the room.',
  },
  proofStats: [
    { value: '30M+', label: 'Views' },
    { value: '118K', label: 'Subs' },
    { value: '$10M', label: 'Pipeline' },
  ],
  audienceFit: {
    eyebrow: 'Who it’s for',
    title: 'Built for one kind of operator.',
    forList: [
      'Top-producing realtors with real volume and a real book',
      'Known in your market, invisible online',
      'Ready to invest once and have it work for years',
    ],
    notForList: [
      'Newer agents still figuring out their niche',
      'Anyone chasing followers instead of clients',
      'Anyone looking for “a few videos” or social management',
    ],
  },
  deliverablesSection: {
    eyebrow: 'What it becomes',
    titleLines: ['One day.', 'Everything you need online.'],
    subhead: 'Built once. Working for years.',
    callout: 'One day of work. Years of trust, on autopilot.',
  },
  deliverables: [
    {
      kicker: '01',
      title: 'Signature Film',
      text: 'The video you send before every listing appointment. Buyers and sellers walk in already knowing who you are, what you do, and why you’re the obvious choice.',
    },
    {
      kicker: '02',
      title: 'Process Film',
      text: 'The film every serious client watches before they sit down with you. Pre-sells the meeting before it starts.',
    },
    {
      kicker: '03',
      title: 'Content Library',
      text: 'A full day of footage, yours forever. Listings, market updates, social — cut new clips for years without filming again.',
    },
    {
      kicker: '04',
      title: 'Homepage',
      text: 'A personal-brand site that reflects what you do — not a brokerage template. The first impression that finally matches your reputation.',
    },
    {
      kicker: '05',
      title: 'Deployment Plan',
      text: 'A simple plan for what posts where and when. So nothing gets dropped after the shoot and your reputation stays in front of buyers.',
      featured: true,
    },
  ],
  storyVideos: [
    {
      eyebrow: 'Signature Film',
      title: 'Signature Film',
      description: 'The link he sends before any serious meeting.',
      ariaLabel: 'Watch the signature film',
      variant: 'waterfront',
      orientation: 'portrait',
      videoSrcMP4: '/videos/roger-story.mp4',
      videoSrcWEBM: '/videos/roger-story.webm',
      poster: '/assets/roger-story-poster.jpg',
      href: 'https://www.youtube.com/watch?v=wUemfee95qI&t=22s',
      startLabel: '',
    },
    {
      eyebrow: 'Pre-Call Film',
      title: 'Pre-Call Film',
      description: 'What every serious prospect sees before the call.',
      ariaLabel: 'Watch the pre-call film',
      variant: 'interior',
      orientation: 'landscape',
      videoSrcMP4: '/videos/sales-preframe.mp4',
      videoSrcWEBM: '/videos/sales-preframe.webm',
      poster: '/assets/sales-preframe-poster.jpg',
      href: 'https://www.youtube.com/watch?v=pFVIjV0LZOI&t=38s',
      startLabel: '',
    },
  ],
  workStrip: {
    eyebrow: 'See the work',
    title: 'This is what being seen looks like.',
    intro:
      'Watch the films that turned Roger from invisible to inevitable in eighteen months.',
    thirdFrame: {
      eyebrow: 'Reel 03',
      title: '90-Day Library',
      description:
        'Twenty-plus short clips, cut from the same day, ready to run for ninety days.',
    },
  },
  authorityCard: {
    eyebrow: 'Proof, not pitch.',
    title: 'Built once. Working every day.',
    intro: 'One Authority Day, three channels of his own.',
    channels: [
      {
        kind: 'site',
        label: 'Homepage',
        anchor: 'pettingellprofessionals.com',
        anchorMono: true,
        primary: 'Where his story lives',
        primaryNote: 'Personal-brand site, not a brokerage page.',
        supporting: 'Sarasota waterfront, on his terms.',
        href: 'https://pettingellprofessionals.com',
        cta: 'Open the site',
        screenshot: '',
      },
      {
        kind: 'youtube',
        label: 'YouTube',
        anchor: '@PettingellProfessionals',
        anchorMono: true,
        primary: '118K',
        primaryNote: 'Subscribers',
        supporting: 'REALTALK™ — 420+ episodes since 2013.',
        href: 'https://www.youtube.com/@PettingellProfessionals',
        cta: 'Watch the show',
      },
      {
        kind: 'instagram',
        label: 'Instagram',
        anchor: '@rogerpettingell',
        anchorMono: true,
        primary: 'Daily presence',
        primaryNote: 'in front of Sarasota buyers.',
        supporting: '6K followers · reels, listings, market notes.',
        href: 'https://www.instagram.com/rogerpettingell',
        cta: 'Follow Roger',
      },
    ],
  },
  story: {
    eyebrow: 'Case Study',
    titleLines: ['Roger Pettingell.'],
    intro: 'Big offline. Invisible online. We fixed that.',
    body: '38 years offline. $3B in sales. Online, almost invisible. One Authority Day. Eighteen months later, his reputation works online the way it always worked in the room.',
    resultsIntro: '',
    results: [
      'His name finally showed up online.',
      'The film became the link before every serious meeting.',
      'The content kept working long after the day.',
    ],
    quote:
      'Jake took everything I built offline and made it visible online. Now it works for me 24/7.',
    quoteAuthor: 'Roger Pettingell',
    quoteRole: 'CEO, Pettingell Group',
    closing: '',
  },
  process: {
    eyebrow: 'Process',
    title: 'How one Authority Day actually runs.',
    steps: [
      {
        step: '01',
        title: 'Pre-work',
        text: 'A 45-minute call. We map the story, the locations, and the shot list.',
        note: '',
      },
      {
        step: '02',
        title: 'The Day',
        text: 'One day on location. We fly to you. We direct. You speak. We capture everything.',
        note: '',
      },
      {
        step: '03',
        title: 'Delivery',
        text: 'Three to four weeks later. Films, clips, homepage, and plan, all installed.',
        note: '',
      },
    ],
  },
  applySection: {
    eyebrow: 'August intake',
    title: 'Start with the right first conversation.',
    primaryCta: 'Apply for a seat',
    primaryHref: '#apply',
    trustLine: applyTrustLine,
    steps: [
      { step: '1', title: 'Apply', text: 'A short form.' },
      {
        step: '2',
        title: 'Call',
        text: 'Fifteen minutes. If it’s not a fit, we’ll say so.',
      },
      {
        step: '3',
        title: 'Authority Day',
        text: 'We build the foundation first. The quarterly system comes after that.',
      },
    ],
  },
};
